//! License header — Doc 00 §10.4.
//!
//! Every generated `.c` and `.h` file starts with an SPDX header block. The
//! header carries the generator version and (for per-machine files) the
//! source filename for traceability.

use crate::config::CodegenConfig;

/// Generator version banner. Bumped manually when the codegen surface
/// changes (the IR version moves independently in `fsm_ir`).
pub const GENERATOR_VERSION: &str = "1.0.0";

/// Build the SPDX header block.
pub fn header_block(config: &CodegenConfig, source_file: Option<&str>) -> String {
    let source_line = source_file
        .map(|s| format!(" * Source: {}\n", s))
        .unwrap_or_default();
    format!(
        "/* SPDX-License-Identifier: {license}\n\
         * Generated by FSM Studio v{ver}\n\
         {source_line} * Do not edit by hand.\n\
         */\n",
        license = config.license_spdx,
        ver = GENERATOR_VERSION,
        source_line = source_line,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_license_emits_mit_spdx_line() {
        let h = header_block(&CodegenConfig::default(), Some("motor.fsm"));
        assert!(h.contains("SPDX-License-Identifier: MIT"));
        assert!(h.contains("Source: motor.fsm"));
        assert!(h.contains("Generated by FSM Studio"));
    }

    #[test]
    fn custom_license_string_propagated_verbatim() {
        let mut cfg = CodegenConfig::default();
        cfg.license_spdx = "Apache-2.0".into();
        let h = header_block(&cfg, None);
        assert!(h.contains("SPDX-License-Identifier: Apache-2.0"));
        // No `Source:` line when source_file is None.
        assert!(!h.contains("Source:"));
    }
}
